#!/usr/bin/env python3
"""Convert the zeroman cart's needleman stage (Zig) into Go source.

Parses `showcase/carts/zeroman/src/stages/needleman.zig` and emits the rooms,
entities and tile attributes as Go. The stage data is otherwise all literals,
so parsing is safer than transcribing a few thousand tile indices by hand.

Usage:
    python3 tools/make_zeroman_stage.py \
        ../sycl-badge/showcase/carts/zeroman/src/stages/needleman.zig \
        > cartridge/zeroman_stage.go
"""

import re
import sys
from pathlib import Path

# The reference stage marks enemy spawns with `.gopher`; in this port the
# player is the gopher and the enemies are the iguanas (see zeroman_enemy.go),
# so map that class to its Go name.
CLASS_NAMES = {"gopher": "Iguana"}


def match_brace(s: str, open_idx: int) -> int:
    depth = 0
    for i in range(open_idx, len(s)):
        if s[i] == "{":
            depth += 1
        elif s[i] == "}":
            depth -= 1
            if depth == 0:
                return i
    raise ValueError("unbalanced braces")


def parse_rooms(s: str) -> list[dict]:
    marker = s.index(".rooms = &[_]Room")
    list_open = s.index("{", marker)
    list_close = match_brace(s, list_open)

    rooms = []
    i = list_open + 1
    while i < list_close:
        if s.startswith("Room{", i):
            end = match_brace(s, i + 4)
            rooms.append(parse_room(s[i : end + 1]))
            i = end + 1
        else:
            i += 1
    return rooms


def parse_room(text: str) -> dict:
    bounds = re.search(
        r"\.bounds = Box\{ \.x = (-?\d+), \.y = (-?\d+), \.w = (-?\d+), \.h = (-?\d+) \}",
        text,
    )
    data = re.search(r"\.data = &\[_\]u8\{(.*?)\}", text, re.S)
    entities = [
        (m.group(1), *(int(v) for v in m.groups()[1:]))
        for m in re.finditer(
            r"Entity\{\s*\.class = \.(\w+),\s*\.box = Box\{ \.x = (-?\d+), \.y = (-?\d+), \.w = (-?\d+), \.h = (-?\d+) \},?\s*\}",
            text,
        )
    ]
    return {
        "width": int(re.search(r"\.width = (\d+)", text).group(1)),
        "height": int(re.search(r"\.height = (\d+)", text).group(1)),
        "bounds": [int(v) for v in bounds.groups()],
        "data": [int(v) for v in re.findall(r"\d+", data.group(1))],
        "entities": entities,
        "door1_y": (int(re.search(r"\.door1_y = (\d+)", text).group(1)) if ".door1_y" in text else None),
        "door2_y": (int(re.search(r"\.door2_y = (\d+)", text).group(1)) if ".door2_y" in text else None),
    }


def parse_attribs(s: str) -> list[str]:
    marker = s.index(".attribs = &[_]Tile.Attrib")
    open_idx = s.index("{", marker)
    close = match_brace(s, open_idx)
    return re.findall(r"\.(none|solid|ladder)", s[open_idx + 1 : close])


def numbers(values: list[int], per_line: int = 16) -> str:
    lines = []
    for i in range(0, len(values), per_line):
        chunk = ", ".join(str(v) for v in values[i : i + per_line])
        lines.append("\t\t\t" + chunk + ",")
    return "\n".join(lines)


def main() -> int:
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(
        "../sycl-badge/showcase/carts/zeroman/src/stages/needleman.zig"
    )
    s = src.read_text()
    rooms = parse_rooms(s)
    attribs = parse_attribs(s)

    out = sys.stdout
    out.write("// Code generated by tools/make_zeroman_stage.py; DO NOT EDIT.\n")
    out.write("//\n")
    out.write("// The needleman stage: rooms, tile attributes and entities.\n\n")
    out.write("package cartridge\n\n")
    out.write("var zeromanAttribs = []tileAttrib{\n")
    for a in attribs:
        out.write(f"\tattrib{a.capitalize()},\n")
    out.write("}\n\n")
    out.write("var zeromanStage = stage{\n\tattribs: zeromanAttribs,\n\trooms: []room{\n")
    for r in rooms:
        x, y, w, h = r["bounds"]
        out.write("\t\t{\n")
        out.write(f"\t\t\twidth: {r['width']}, height: {r['height']},\n")
        out.write(f"\t\t\tbounds: box{{x: {x}, y: {y}, w: {w}, h: {h}}},\n")
        door1 = r["door1_y"] if r["door1_y"] is not None else "noDoor"
        door2 = r["door2_y"] if r["door2_y"] is not None else "noDoor"
        out.write(f"\t\t\tdoor1Y: {door1}, door2Y: {door2},\n")
        out.write("\t\t\tdata: []byte{\n")
        out.write(numbers(r["data"]))
        out.write("\n\t\t\t},\n")
        if r["entities"]:
            out.write("\t\t\tentities: []entity{\n")
            for cls, ex, ey, ew, eh in r["entities"]:
                out.write(
                    f"\t\t\t\t{{class: class{CLASS_NAMES.get(cls, cls.capitalize())}, "
                    f"box: box{{x: {ex}, y: {ey}, w: {ew}, h: {eh}}}}},\n"
                )
            out.write("\t\t\t},\n")
        out.write("\t\t},\n")
    out.write("\t},\n}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
