#!/usr/bin/env python3
"""Extract the badge's 8x8 bitmap font into Go source for the cartridge menu.

The reference firmware (../sycl-badge) ships the platform font as a Zig array
(`src/font.zig`), 224 glyphs (0x20..0xFF) of 8 bytes each. The cartridge
platform only needs printable ASCII (0x20..0x7E), so this emits that subset.

Each byte is one glyph row, MSB = leftmost pixel. A clear bit (0) is ink and a
set bit (1) is background, matching the reference `cart.text()` renderer.

Usage:
    python3 tools/make_font.py > cartridge/font_data.go
    python3 tools/make_font.py ../sycl-badge/src/font.zig > cartridge/font_data.go
"""

import re
import sys
from pathlib import Path

FIRST = 0x20
LAST = 0x7E


def parse_font(path: Path) -> list[list[int]]:
    rows = [int(m, 2) for m in re.findall(r"0b([01]{8})", path.read_text())]
    if len(rows) % 8 != 0:
        raise SystemExit(f"{path}: expected a multiple of 8 rows, got {len(rows)}")
    return [rows[i : i + 8] for i in range(0, len(rows), 8)]


def main() -> int:
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("../sycl-badge/src/font.zig")
    if not src.is_file():
        raise SystemExit(f"font source not found: {src}")
    glyphs = parse_font(src)
    if len(glyphs) < LAST - FIRST + 1:
        raise SystemExit(f"{src}: only {len(glyphs)} glyphs, need {LAST - FIRST + 1}")

    out = sys.stdout
    out.write("// Code generated by tools/make_font.py; DO NOT EDIT.\n")
    out.write("//\n")
    out.write("// 8x8 bitmap font for printable ASCII (0x20..0x7E), extracted from the\n")
    out.write("// reference firmware's src/font.zig. MSB is the leftmost pixel; a clear\n")
    out.write("// bit (0) is ink.\n\n")
    out.write("package cartridge\n\n")
    out.write(f"// font8x8 covers ASCII 0x{FIRST:02X}..0x{LAST:02X}.\n")
    out.write("var font8x8 = [%d][8]uint8{\n" % (LAST - FIRST + 1))
    for ch in range(FIRST, LAST + 1):
        g = glyphs[ch - FIRST]
        cells = ", ".join(f"0x{b:02X}" for b in g)
        out.write(f"\t{{{cells}}}, // {chr(ch)!r}\n")
    out.write("}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
