#!/usr/bin/env python3
"""Convert the zeroman cart's PNG assets into a Go source file.

Mirrors the reference cart's `build/convert_gfx.zig`: each image becomes a
palette of RGB565 colors plus bit-packed palette indices (1, 2 or 4 bits per
pixel, LSB-first within each byte). Magenta (RGB 255,0,255) is the transparent
sentinel, exactly as in the reference art, and the renderer skips it.

Usage:
    python3 tools/make_zeroman_gfx.py \
        ../sycl-badge/showcase/carts/zeroman/assets > cartridge/zeroman_gfx.go
"""

import sys
from pathlib import Path

from PIL import Image

# (goName, file stem, bits per pixel). 2**bits must fit the palette.
ASSETS = [
    ("Needleman", "needleman", 4),
    ("Door", "door", 2),
    ("Effects", "effects", 2),
    ("Font", "font", 2),
    ("Gopher", "gopher", 4),
    ("Healthbar", "healthbar", 4),
    ("Hurt", "hurt", 1),
    ("Shot", "shot", 2),
    ("Spike", "spike", 2),
    ("Teleport", "teleport", 2),
    ("Title", "title", 4),
    ("Zero", "zero", 4),
]


def rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def pack_indices(indices: list[int], bits: int) -> list[int]:
    per_byte = 8 // bits
    out = []
    for i in range(0, len(indices), per_byte):
        byte = 0
        for n in range(per_byte):
            byte |= indices[i + n] << (n * bits)
        out.append(byte)
    return out


def convert(path: Path, bits: int) -> tuple[int, int, list[int], list[int]]:
    img = Image.open(path).convert("RGB")
    w, h = img.size
    palette: list[int] = []
    lookup: dict[int, int] = {}
    indices: list[int] = []
    for r, g, b in img.getdata():
        c = rgb565(r, g, b)
        idx = lookup.get(c)
        if idx is None:
            idx = len(palette)
            if idx >= (1 << bits):
                raise SystemExit(f"{path.name}: palette exceeds {1 << bits} colors")
            palette.append(c)
            lookup[c] = idx
        indices.append(idx)
    return w, h, palette, pack_indices(indices, bits)


def bytes_literal(data: list[int]) -> str:
    lines = []
    for i in range(0, len(data), 24):
        chunk = ", ".join(str(b) for b in data[i : i + 24])
        lines.append("\t" + chunk + ",")
    return "\n".join(lines)


def main() -> int:
    assets_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(
        "../sycl-badge/showcase/carts/zeroman/assets"
    )
    out = sys.stdout
    out.write("// Code generated by tools/make_zeroman_gfx.py; DO NOT EDIT.\n")
    out.write("//\n")
    out.write("// zeroman sprite and tilesheet art as RGB565 palettes plus bit-packed\n")
    out.write("// indices. Magenta is the transparent sentinel.\n\n")
    out.write("package cartridge\n\n")
    for name, stem, bits in ASSETS:
        w, h, palette, packed = convert(assets_dir / f"{stem}.png", bits)
        colors = ", ".join(f"0x{c:04X}" for c in palette)
        out.write(f"var gfx{name} = gfxImage{{\n")
        out.write(f"\tw: {w}, h: {h}, bits: {bits},\n")
        out.write(f"\tcolors: []uint16{{{colors}}},\n")
        out.write(f"\tindices: []byte{{\n{bytes_literal(packed)}\n\t}},\n")
        out.write("}\n\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
