#!/usr/bin/env python3
"""Convert the Go gopher PNG into a Go source file of RGB565 pixels.

The gopher is by Renee French, licensed CC BY 3.0:
https://go.dev/wiki/Gopher

The output is a []byte in the byte order the ST7735 panel expects on the wire
(RGB565, high byte first), which is what tinygo.org/x/drivers encodes as
pixel.RGB565BE.

Usage:
    python3 tools/make_gopher.py assets/gopher.png > gopher_data.go
"""

import argparse
import sys

from PIL import Image

# Target draw size. The panel is 160x128; keep the portrait gopher within it.
MAX_W = 96
MAX_H = 118


def to_rgb565(r: int, g: int, b: int) -> int:
    """Pack 8-bit RGB into native RGB565."""
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("image", help="path to the gopher PNG")
    ap.add_argument("--width", type=int, default=MAX_W)
    ap.add_argument("--height", type=int, default=MAX_H)
    args = ap.parse_args()

    img = Image.open(args.image).convert("RGBA")

    # Composite onto black so transparent pixels become black, not white.
    bg = Image.new("RGBA", img.size, (0, 0, 0, 255))
    img = Image.alpha_composite(bg, img).convert("RGB")

    # Preserve aspect ratio within the box.
    img.thumbnail((args.width, args.height), Image.LANCZOS)
    w, h = img.size

    out = sys.stdout
    out.write("// Code generated by tools/make_gopher.py; DO NOT EDIT.\n")
    out.write("//\n")
    out.write("// The Go gopher was designed by Renee French and is licensed under\n")
    out.write("// the Creative Commons 3.0 Attribution license (CC BY 3.0).\n")
    out.write("// https://go.dev/wiki/Gopher\n\n")
    out.write("package main\n\n")
    out.write("const (\n")
    out.write(f"\tgopherWidth  = {w}\n")
    out.write(f"\tgopherHeight = {h}\n")
    out.write(")\n\n")

    # Emit RGB565 bytes, high byte first, matching pixel.RGB565BE's wire layout.
    out.write("// gopherData is gopherWidth*gopherHeight*2 bytes of RGB565 pixels\n")
    out.write("// (high byte first), row-major.\n")
    out.write("var gopherData = [...]byte{\n")
    px = img.getdata()
    for y in range(h):
        row = []
        for x in range(w):
            r, g, b = px[y * w + x]
            v = to_rgb565(r, g, b)
            row.append(v >> 8)
            row.append(v & 0xFF)
        out.write("\t")
        out.write(", ".join(f"0x{v:02X}" for v in row))
        out.write(",\n")
    out.write("}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
